name: Publish Desktop App to GitHub Releases

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build desktop binaries
    runs-on: ${{ matrix.os }}
    environment:
      name: github-releases
    env:
      NODE_ENV: production
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_WEBSOCKET_URL: ${{ secrets.VITE_WEBSOCKET_URL }}
      VITE_PUBLIC_WEB_BASE_URL: ${{ secrets.VITE_PUBLIC_WEB_BASE_URL }}
      VITE_DEEP_LINK_PROTOCOL: ${{ secrets.VITE_DEEP_LINK_PROTOCOL }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Disable Windows CRLF translation
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git reset --hard

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter="!game-api" --frozen-lockfile

      - name: Build desktop app
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: Build desktop app
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      - name: Build desktop app
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build:linux

      - name: Archive production artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ matrix.os }}
          path: |
            apps/desktop/dist/**
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: dist-* # grab all platform artifacts
          merge-multiple: true
          path: dist

      - name: Create / Update GitHub Release & Upload Assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: "dist/**"
          artifactErrorsFailBuild: true
          draft: false
          generateReleaseNotes: true
          allowUpdates: true 
